language: node_js
node_js:
  - '8.10'
sudo: false
before_install:
  - npm install -g yarn
install:
  - yarn
script:
  - yarn run build
deploy:
  provider: pages
  local_dir: ./dist
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  on:
    branch: master
